INSERT INTO `module_config` (`config`, `value`, `comment`) VALUES
    ('Npc_Titles.Enable', 1, NULL),
    ('Npc_Titles.Announce', 1, NULL),
    ('Npc_Titles.Cost', 10, "Amount in gold (not copper)"),
    ("Npc_Titles.Glad.Rating", 0, NULL),
    ("Npc_Titles.Glad.ItemID", 0, NULL),
    ("Npc_Titles.Glad.ItemCount", 0, NULL),
    ("Npc_Titles.Glad.Honor", 0, NULL),
    ("Npc_Titles.Glad.Ap", 0, NULL),
    ("Npc_Titles.MGlad.Gold", 10, "Amount in gold (not copper)"),
    ("Npc_Titles.MGlad.Rating", 0, NULL),
    ("Npc_Titles.MGlad.ItemID", 0, NULL),
    ("Npc_Titles.MGlad.ItemCount", 0, NULL),
    ("Npc_Titles.MGlad.Honor", 0, NULL),
    ("Npc_Titles.MGlad.Ap", 0, NULL),
    ("Npc_Titles.VGlad.Gold", 10, "Amount in gold (not copper)"),
    ("Npc_Titles.VGlad.Rating", 0, NULL),
    ("Npc_Titles.VGlad.ItemID", 0, NULL),
    ("Npc_Titles.VGlad.ItemCount", 0, NULL),
    ("Npc_Titles.VGlad.Honor", 0, NULL),
    ("Npc_Titles.VGlad.Ap", 0, NULL);